server:
  address: 0.0.0.0
  port: 82
spring:
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动     #
    url: jdbc:mysql://*:3306/stream-data?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai 
    username: root #测试 
    password: 123456 #测试 
    ##########################  druid配置   ########################## 
    type: com.alibaba.druid.pool.DruidDataSource 
    druid:  
      max-active: 20      # 初始化大小，最小，最大 
      initial-size: 3
      min-idle: 3
      max-wait: 60000       # 配置获取连接等待超时的时间 
      time-between-eviction-runs-millis: 60000         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
      min-evictable-idle-time-millis: 300000           # 配置一个连接在池中最小生存的时间，单位是毫秒 
      validation-query: select 'x'                  # 校验SQL，Oracle配置 validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用 
      #      validation-query-timeout: 
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 打开PSCache，并且指定每个连接上PSCache的大小 
      max-open-prepared-statements: 20
      filters: stat                                # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 wall,log4j 
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000       # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 
      useGlobalDataSourceStat: true               # 合并多个DruidDataSource的监控数据 
      asyncInit: true

  redis:
    timeout: 60000
    lettuce:
      pool:
        max-active: 1024
        max-idle: 100
        max-wait: 30
        min-idle: 20
  data-redis:
    host: 192.168.5.115
    password:
    port: 6379
    database: 4
  session-redis:
    host: 192.168.5.115
    password:
    port: 6379
    database: 0

  cache:
    type: redis

cache:
  expireTime: 100000




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:  com.archly.data.source.endpoint.web.persistence.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: file:config/logback-spring-prod.xml